- name: Add host entiries for the Docker containers 
  hosts: custom-desktop-box
  tasks:
      - name: Copy hostname script to a safe place
        copy: src=scripts/add-host-name.sh dest=/tmp/add-host-name.sh owner=root group=root mode=755 backup=no
      - name: Add docker to hostfile
        command: /tmp/add-host-name.sh docker 192.168.44.60
      - name: Add rabbitmq to hostfile
        command: /tmp/add-host-name.sh rabbitmq 192.168.44.30
      - name: Add mongodb to hostfile
        command: /tmp/add-host-name.sh mongodb 192.168.44.30
      - name: Add mongo to hostfile
        command: /tmp/add-host-name.sh mongo 192.168.44.30
      - name: Add mysql to hostfile
        command: /tmp/add-host-name.sh mysql 192.168.44.30
      - name: Add redis to hostfile
        command: /tmp/add-host-name.sh redis 192.168.44.30
      - name: Add memcached to hostfile
        command: /tmp/add-host-name.sh memcached 192.168.44.30
      - name: Add elasticsearch to hostfile
        command: /tmp/add-host-name.sh elasticsearch 192.168.44.30
      - name: Add nginx to hostfile
        command: /tmp/add-host-name.sh nginx 192.168.44.30
      - name: Add postgresql to hostfile
        command: /tmp/add-host-name.sh postgresql 192.168.44.30
      - name: Add logfaces to hostfile 
        command: /tmp/add-host-name.sh logfaces 192.168.254.123 
      - name: Add logfaces-boston to hostfile 
        command: /tmp/add-host-name.sh logfaces-boston 192.168.100.124 
      - name: Add mongo1test to hostfile 
        command: /tmp/add-host-name.sh mongo1test 192.168.254.57 
      - name: Add mongo2test to hostfile 
        command: /tmp/add-host-name.sh mongo1test 192.168.254.58 
      - name: Add mongo3test to hostfile 
        command: /tmp/add-host-name.sh mongo1test 192.168.254.59 
      - name: Add stagetwo to hostfile 
        command: /tmp/add-host-name.sh stagetwo 192.168.255.29 
      - name: Add cd0 to hostfile 
        command: /tmp/add-host-name.sh cd0 192.168.254.85 
      - name: Add cd1 to hostfile 
        command: /tmp/add-host-name.sh cd1 192.168.254.81 
      - name: Add cd5 to hostfile 
        command: /tmp/add-host-name.sh cd5 192.168.254.114 
      - name: Add cd6 to hostfile 
        command: /tmp/add-host-name.sh cd6 192.168.254.59 
      - name: Add rabbit-test to hostfile 
        command: /tmp/add-host-name.sh rabbit-test 192.168.254.28 
      - name: Add registry.transparent.com to hostfile
        command: /tmp/add-host-name.sh registry.transparent.com 192.168.254.90

- name: Make per-project tweaks to RabbitMQ 
  hosts: custom-desktop-box
  tasks:
    - name: Copy hostname script to a safe place
      copy: src=scripts/add-virtualhost.sh dest=/tmp/add-virtualhost.sh owner=root group=root mode=755 backup=no
    - name: Add Sush-E virtual host 
      command: /tmp/add-virtualhost.sh sush-e rabbitmq guest guest
    - name: Add Mold-E virtual host 
      command: /tmp/add-virtualhost.sh mold-e rabbitmq guest guest
    - name: Add Asgard virtual host 
      command: /tmp/add-virtualhost.sh asgard rabbitmq guest guest
    - name: Add Khujand virtual host 
      command: /tmp/add-virtualhost.sh khujand rabbitmq guest guest

- name: Create custom databases 
  hosts: custom-desktop-box
  tasks:
    - name: Installing required dependencies so we can use Ansible MySQL modules
      apt: name={{ item }} state=present
      with_items:
        - mysql-client
        - python-mysqldb
    - name: Sush-E Database 
      mysql_db: name=sushe state=present encoding=utf8 collation=utf8_general_ci login_host=mysql login_user=root login_password=mysql

- name: Custom Desktop tweeks 
  hosts: custom-desktop-box
  tasks:
      - name: Install custom desktop packages
        apt: "name={{ item }} state=present"
        with_items:
           - cvs 
      - name: Create Asgard project directory
        file: path=/home/vagrant/Stash/Asgard state=directory
      - name: Create Gradle project directory
        file: path=/home/vagrant/Stash/Gradle state=directory
      - name: Create Khujand project directory
        file: path=/home/vagrant/Stash/Khujand state=directory
      - name: Create Mold-E project directory
        file: path=/home/vagrant/Stash/Mold-E state=directory
      - name: Create Sush-E project directory
        file: path=/home/vagrant/Stash/Sush-E state=directory
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory
      - name: Copy alias change script to a safe place
        copy: src=scripts/add-alias.sh dest=/tmp/add-alias.sh owner=root group=root mode=755 backup=no
      - name: add an alias to quickly change to the Asgard directory
        command: /tmp/add-alias.sh asgard 'cd /home/vagrant/Stash/Asgard'
      - name: add an alias to quickly change to the Mold-E directory
        command: /tmp/add-alias.sh molde 'cd /home/vagrant/Stash/Mold-E'
      - name: add an alias to quickly change to the Sush-E directory
        command: /tmp/add-alias.sh sushe 'cd /home/vagrant/Stash/Sush-E'
