- name: Custom Desktop tweeks 
  hosts: custom-desktop-box
  tasks:
      - name: Install custom desktop packages
        apt: "name={{ item }} state=present"
        with_items:
           - cvs 
      - name: Copy hostname script to a safe place
        copy: src=scripts/add-host-name.sh dest=/tmp/add-host-name.sh owner=root group=root mode=755 backup=no
      - name: Add docker to hostfile 
        command: /tmp/add-host-name.sh docker 192.168.44.60
      - name: Copy etc change script to a safe place
        copy: src=scripts/set-etc-environment.sh dest=/tmp/set-etc-environment.sh owner=root group=root mode=755 backup=no
      - name: Add silly environment variable 
        command: /tmp/set-etc-environment.sh RON_WAS_HERE true 
