- hosts: all
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Upgrade currently installed packages
        apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"

      - name: Install common packages
        apt: "name={{ item }} state=present"
        with_items:
           - tree
           - aptitude
           - iftop
           - python-apt
           - curl
           - telnet
           - apt-transport-https

- hosts: passwordless-sudo-box
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Copy the sudoers file
        copy: src=files/passwordless-sudo dest=/etc/sudoers.d/passwordless-sudo owner=root group=root mode=0440 backup=no

- hosts: remote-managed
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install Webmin keys
        apt_key: url='http://www.webmin.com/jcameron-key.asc' state=present
      - name: Install primary Webmin repository
        apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present 
      - name: Install secondary Webmin repository
        apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' state=present 
      - name: Install Webmin software
        apt: name=webmin state=latest update_cache=true cache_valid_time=600

- hosts: java-8-box
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Create destination directory 
        file: path=/usr/lib/jvm owner=root group=root state=directory mode=755
      - name: Copy JDK 8 download script to a safe place
        copy: src=scripts/download-jdk-8.sh dest=/tmp/download-jdk-8.sh owner=root group=root mode=755 backup=no
      - name: Execute download script 
        command: /tmp/download-jdk-8.sh
      - name: unpack the archive
        unarchive: src=/tmp/jdk-8.tar.gz dest=/usr/lib/jvm copy=no owner=root group=root mode=755
      - name: soft-link the JDK to a normalized location
        file: src=/usr/lib/jvm/jdk1.8.0_25 dest=/usr/lib/jvm/oracle-jdk-8 owner=root group=root state=link
      - name: Copy export script to a safe place
        copy: src=scripts/export-java-home.sh dest=/tmp/export-java-home.sh owner=root group=root mode=755 backup=no
      - name: Execute JDK export script 
        command: /tmp/export-java-home.sh

- hosts: java-7-box
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Create destination directory 
        file: path=/usr/lib/jvm owner=root group=root state=directory mode=755
      - name: Copy JDK 7 download script to a safe place
        copy: src=scripts/download-jdk-7.sh dest=/tmp/download-jdk-7.sh owner=root group=root mode=755 backup=no
      - name: Execute download script 
        command: /tmp/download-jdk-7.sh
      - name: unpack the archive
        unarchive: src=/tmp/jdk-7.tar.gz dest=/usr/lib/jvm copy=no owner=root group=root mode=755
      - name: soft-link the JDK to a normalized location
        file: src=/usr/lib/jvm/jdk1.7.0_71 dest=/usr/lib/jvm/oracle-jdk-7 owner=root group=root state=link

- hosts: groovy-developer
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Copy GVM installation script to a safe place
        copy: src=scripts/install-gvm.sh dest=/tmp/install-gvm.sh owner=vagrant group=vagrant mode=755 backup=no
      - name: Install GVM 
        shell: sudo --user vagrant --set-home --non-interactive --login /tmp/install-gvm.sh --
      - name: Copy GVM configuration file
        copy: src=files/gvm.config dest=/home/vagrant/.gvm/etc/config owner=vagrant group=vagrant mode=644 backup=no

- hosts: intellij-user
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Create Software directory 
        file: path=/home/vagrant/Software owner=vagrant group=vagrant state=directory mode=755
      - name: Download IntelliJ IDEA 
        get_url: url=http://download.jetbrains.com/idea/ideaIU-14.tar.gz dest=/tmp mode=444 
      - name: Unpack IntelliJ IDEA 
        unarchive: src=/tmp/ideaIU-14.tar.gz dest=/home/vagrant/Software copy=no owner=vagrant group=vagrant
      - name: Soft-link IntelliJ 
        file: src=/home/vagrant/Software/idea-IU-139.224.1 path=/home/vagrant/Software/idea state=link
      - name: Create Desktop directory 
        file: path=/home/vagrant/Desktop owner=vagrant group=vagrant state=directory mode=755
      - name: Copy desktop IntelliJ file  
        copy: src=files/InjelliJ.desktop dest=/home/vagrant/Desktop/InjelliJ.desktop owner=vagrant group=vagrant backup=no mode=755
      - name: Copy export script to a safe place
        copy: src=scripts/export-idea-jdk.sh dest=/tmp/export-idea-jdk.sh owner=root group=root mode=755 backup=no
      - name: Execute IDEA export script 
        command: /tmp/export-idea-jdk.sh


- hosts: docker-box
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install Docker keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      - name: Install Docker repository
        apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
      - name: Install Docker 
        apt: name=lxc-docker state=latest update_cache=true cache_valid_time=600
      - name: Add vagrant to the docker group
        user: name=vagrant state=present groups=docker
      - name: Set Memory and Swap Accounting
        lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
      - name: Rebuild GRUB 
        command: update-grub
      - name: Restart Docker 
        service: name=docker state=restarted 

- hosts: desktops
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install desktop packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - wireshark
           - chromium-browser
      - name: Copy login icon  
        copy: src=files/brock.png dest=/home/vagrant/.face owner=vagrant group=vagrant backup=no mode=644

